### ISSUE TITLE
Error on macOS Ventura 13.5 M1

### ISSUE THREAD

**Issue by 19marine91** [abdnh/AnkiApp-importer#4]
Good morning !

I'm on a 2020 Mac mini M1.

I downloaded decks made by me from Ankiapp (one of which I had started with Anki, I want to go back there!).
Normally, I did everything as you said in Anki (this is my 1st addon):
Tools > Add-ons > Get-addons and I entered 2072125761;
Restart;
I'm looking in the file in Finder;
In the Anki app, Tools > Import from Anki > file location.
I immediately get an error message recommending me to restart Anki without add-ons to see if the problem persists (I admit I didn't do it ^^')
I tried with the file in the original location then copy to Documents. I tried with the app in French, English, restarted Anki, Anki app (opened then closed during the process), restarted the computer.

Below is the error message if it helps.

Thank you anyway !

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-13.5-arm64-arm-64bit
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-08-24 18:30:38
Add-ons possibly involved: ⁨AnkiApp Importer⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/marine_redac/Library/Application Support/Anki2/addons21/2072125761/ankiapp_importer.py", line 190, in __init__
    ext = self.extensions_for_mimes[mime]
KeyError: 'audio/mp3'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "/Users/marine_redac/Library/Application Support/Anki2/addons21/2072125761/__init__.py", line 26, in on_done
    count, warnings = fut.result()
  File "concurrent.futures._base", line 439, in result
  File "concurrent.futures._base", line 391, in __get_result
  File "concurrent.futures.thread", line 58, in run
  File "/Users/marine_redac/Library/Application Support/Anki2/addons21/2072125761/__init__.py", line 20, in start_importing
    importer = AnkiAppImporter(mw, filename)
  File "/Users/marine_redac/Library/Application Support/Anki2/addons21/2072125761/ankiapp_importer.py", line 231, in __init__
    self._extract_media()
  File "/Users/marine_redac/Library/Application Support/Anki2/addons21/2072125761/ankiapp_importer.py", line 281, in _extract_media
    self.media[ID] = Media(ID, mime, base64.b64decode(data))
  File "/Users/marine_redac/Library/Application Support/Anki2/addons21/2072125761/ankiapp_importer.py", line 192, in __init__
    raise Exception(f"unrecognized mime type: {mime}") from exc
Exception: unrecognized mime type: audio/mp3
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-13.5-arm64-arm-64bit
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-08-24 18:30:38
Add-ons possibly involved: ⁨AnkiApp Importer⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/marine_redac/Library/Application Support/Anki2/addons21/2072125761/ankiapp_importer.py", line 190, in __init__
    ext = self.extensions_for_mimes[mime]
KeyError: 'audio/mp3'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "/Users/marine_redac/Library/Application Support/Anki2/addons21/2072125761/__init__.py", line 26, in on_done
    count, warnings = fut.result()
  File "concurrent.futures._base", line 439, in result
  File "concurrent.futures._base", line 391, in __get_result
  File "concurrent.futures.thread", line 58, in run
  File "/Users/marine_redac/Library/Application Support/Anki2/addons21/2072125761/__init__.py", line 20, in start_importing
    importer = AnkiAppImporter(mw, filename)
  File "/Users/marine_redac/Library/Application Support/Anki2/addons21/2072125761/ankiapp_importer.py", line 231, in __init__
    self._extract_media()
  File "/Users/marine_redac/Library/Application Support/Anki2/addons21/2072125761/ankiapp_importer.py", line 281, in _extract_media
    self.media[ID] = Media(ID, mime, base64.b64decode(data))
  File "/Users/marine_redac/Library/Application Support/Anki2/addons21/2072125761/ankiapp_importer.py", line 192, in __init__
    raise Exception(f"unrecognized mime type: {mime}") from exc
Exception: unrecognized mime type: audio/mp3

**Comment by abdnh** [comment]
This seems to be something related to your system. I released a workaround. Let me know if it still doesn't work after you update.

**Comment by 19marine91** [comment]
That works ! Fast and effective ! Thank you so much
